# Setup
title:               Lioncash
encoding:            "utf-8"

# About/contact
author:
  name:              Lioncash
  email:             "" # email here
  #avatar:           img/avatar.jpg
  #profile-pic:      img/profile-pic.jpg

# URL
permalink:           /:year/:month/:day/:title

# Inclusions
include: ["_other"]

# Build settings
markdown:            kramdown
kramdown:
  input:             "GFM"

sass:
  sass_dir:          _sass
  style:             :compressed

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Lioncash
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"