# Basic
name:               "Lioncash's blog"
encoding:           "utf-8"

# URL
baseurl:            ""
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "header/about"
  - name:           "Other stuff"
    href:           "header/other-stuff"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
